"""empty message

Revision ID: 1de4df2fbc60
Revises: 3d9e3d65e771
Create Date: 2018-01-10 16:17:57.719000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1de4df2fbc60'
down_revision = '3d9e3d65e771'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'body1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('body1', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
