"""empty message

Revision ID: 1edd13c438e5
Revises: 1de4df2fbc60
Create Date: 2018-01-10 16:19:06.494000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1edd13c438e5'
down_revision = '1de4df2fbc60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'body')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('body', mysql.VARCHAR(length=150), nullable=True))
    # ### end Alembic commands ###
