"""'test'

Revision ID: 3d9e3d65e771
Revises: c7ad11f292f0
Create Date: 2018-01-10 16:16:39.253000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d9e3d65e771'
down_revision = 'c7ad11f292f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('body1', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'body1')
    # ### end Alembic commands ###
