"""empty message

Revision ID: 52ac3a894e00
Revises: 8365cb2e0787
Create Date: 2018-01-04 19:12:21.699000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52ac3a894e00'
down_revision = '8365cb2e0787'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hpf', sa.String(length=10), nullable=True))
    op.create_index(op.f('ix_user_hpf'), 'user', ['hpf'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_hpf'), table_name='user')
    op.drop_column('user', 'hpf')
    # ### end Alembic commands ###
