"""empty message

Revision ID: 7151d6aaaafa
Revises: 52ac3a894e00
Create Date: 2018-01-05 09:48:34.940000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7151d6aaaafa'
down_revision = '52ac3a894e00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('username', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.drop_index('ix_user_email', table_name='user')
    op.drop_index('ix_user_hpf', table_name='user')
    op.drop_index('ix_user_nickname', table_name='user')
    op.drop_column('user', 'nickname')
    op.drop_column('user', 'email')
    op.drop_column('user', 'hpf')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hpf', mysql.VARCHAR(length=10), nullable=True))
    op.add_column('user', sa.Column('email', mysql.VARCHAR(length=120), nullable=True))
    op.add_column('user', sa.Column('nickname', mysql.VARCHAR(length=64), nullable=True))
    op.create_index('ix_user_nickname', 'user', ['nickname'], unique=True)
    op.create_index('ix_user_hpf', 'user', ['hpf'], unique=True)
    op.create_index('ix_user_email', 'user', ['email'], unique=True)
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_column('user', 'username')
    op.drop_column('user', 'password_hash')
    # ### end Alembic commands ###
